# Builds bin\DSLRWebcamStudio.exe: a single file with the virtual-camera DLL embedded.
#  - The app uses the C# compiler that ships with Windows (.NET Framework 4.8).
#  - The virtual camera (C++) is built with Zig's portable clang toolchain, downloaded on first use
#    into windows\.tools (or set $env:ZIG to an existing zig.exe).
# No Visual Studio, SDK, NuGet packages or Canon DLLs required.
param([string]$Out)  # optional output path (default binDSLRWebcamStudio.exe)
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$repo = Split-Path $root -Parent
$bin = Join-Path $root 'bin'
$gen = Join-Path $root 'obj'
New-Item -ItemType Directory -Force $bin, $gen | Out-Null

# ---- virtual camera DLL --------------------------------------------------------------------------
$zigVersion = '0.13.0'
$zig = $env:ZIG
if (-not $zig) {
    $zig = Join-Path $root ".tools\zig-windows-x86_64-$zigVersion\zig.exe"
    if (-not (Test-Path $zig)) {
        $tools = Join-Path $root '.tools'
        New-Item -ItemType Directory -Force $tools | Out-Null
        $zip = Join-Path $tools 'zig.zip'
        Write-Host "Downloading Zig $zigVersion (C++ toolchain for the virtual camera)..."
        Invoke-WebRequest "https://ziglang.org/download/$zigVersion/zig-windows-x86_64-$zigVersion.zip" -OutFile $zip
        Expand-Archive $zip -DestinationPath $tools -Force
        Remove-Item $zip
    }
}
$vcam = Join-Path $root 'vcam'
$dll = Join-Path $bin 'DSLRWebcamStudioVCam.dll'
& $zig cc -target x86_64-windows-gnu -shared -O2 -x c++ -std=c++17 -fno-exceptions -fno-rtti -Wall -Wno-unknown-pragmas `
    -o $dll (Join-Path $vcam 'vcam.cpp') -x none (Join-Path $vcam 'vcam.def') -lmfplat -lmf -lole32 -ladvapi32 -luser32
if ($LASTEXITCODE -ne 0) { throw "virtual camera build failed" }
Remove-Item (Join-Path $bin 'DSLRWebcamStudioVCam.lib'), (Join-Path $bin 'DSLRWebcamStudioVCam.pdb') -ErrorAction SilentlyContinue

# Media-source test harness (run by CI): exercises the DLL through Windows' IMFSourceReader.
& $zig c++ -target x86_64-windows-gnu -O1 -o (Join-Path $bin 'test_vcam.exe') (Join-Path $vcam 'test_vcam.cpp') `
    -lmfplat -lmfreadwrite -lmfuuid -lole32 2>$null
if ($LASTEXITCODE -ne 0) { throw "virtual camera test build failed" }
Remove-Item (Join-Path $bin 'test_vcam.pdb') -ErrorAction SilentlyContinue

# ---- app --------------------------------------------------------------------------------------------
$csc = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe'
if (-not (Test-Path $csc)) { throw ".NET Framework 4.x C# compiler not found at $csc" }

# Version and donation link come from the repo-root files shared by all three apps.
$version = (Get-Content (Join-Path $repo 'VERSION') -Raw).Trim()
$donate = (Get-Content (Join-Path $repo 'DONATE_URL') -Raw).Trim()
$appInfo = Join-Path $gen 'AppInfo.g.cs'
@"
// Generated by build.ps1 from VERSION and DONATE_URL. Do not edit.
[assembly: System.Reflection.AssemblyVersion("$version.0")]
[assembly: System.Reflection.AssemblyFileVersion("$version.0")]
namespace DslrWebcamStudio
{
    static class AppInfo
    {
        public const string Version = "$version";
        public const string DonateUrl = "$donate";
        public const string RepoUrl = "https://github.com/akshay4/dslr-webcam-studio";
        // The button stays hidden until DONATE_URL holds a real link.
        public static bool DonateConfigured { get { return !DonateUrl.Contains("YOUR_PAYPAL_NAME") && DonateUrl.StartsWith("https://"); } }
    }
}
"@ | Set-Content -Encoding UTF8 $appInfo

$out = if ($Out) { $Out } else { Join-Path $bin 'DSLRWebcamStudio.exe' }
$sources = @(Get-ChildItem (Join-Path $root 'src') -Filter *.cs | ForEach-Object { $_.FullName }) + $appInfo

& $csc -nologo -target:winexe -platform:x64 -optimize+ -unsafe+ -warn:4 `
    "-out:$out" `
    "-win32manifest:$(Join-Path $root 'app.manifest')" `
    "-win32icon:$(Join-Path $repo 'assets\icon.ico')" `
    "-resource:$dll,DSLRWebcamStudioVCam.dll" `
    -reference:System.Drawing.dll -reference:System.Windows.Forms.dll `
    $sources
if ($LASTEXITCODE -ne 0) { throw "build failed" }
"Built $out v$version ({0:N0} KB, virtual camera embedded)" -f ((Get-Item $out).Length / 1KB)
