# Builds bin\DSLRWebcamStudio.exe with the C# compiler that ships with Windows (.NET Framework 4.8).
# No SDK, NuGet packages or Canon DLLs required.
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$repo = Split-Path $root -Parent
$csc = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe'
if (-not (Test-Path $csc)) { throw ".NET Framework 4.x C# compiler not found at $csc" }

# Version and donation link come from the repo-root files shared by all three apps.
$version = (Get-Content (Join-Path $repo 'VERSION') -Raw).Trim()
$donate = (Get-Content (Join-Path $repo 'DONATE_URL') -Raw).Trim()
$gen = Join-Path $root 'obj'
New-Item -ItemType Directory -Force $gen | Out-Null
$appInfo = Join-Path $gen 'AppInfo.g.cs'
@"
// Generated by build.ps1 from VERSION and DONATE_URL. Do not edit.
[assembly: System.Reflection.AssemblyVersion("$version.0")]
[assembly: System.Reflection.AssemblyFileVersion("$version.0")]
namespace DslrWebcamStudio
{
    static class AppInfo
    {
        public const string Version = "$version";
        public const string DonateUrl = "$donate";
        public const string RepoUrl = "https://github.com/akshay4/dslr-webcam-studio";
        // The button stays hidden until DONATE_URL holds a real link.
        public static bool DonateConfigured { get { return !DonateUrl.Contains("YOUR_PAYPAL_NAME") && DonateUrl.StartsWith("https://"); } }
    }
}
"@ | Set-Content -Encoding UTF8 $appInfo

$bin = Join-Path $root 'bin'
New-Item -ItemType Directory -Force $bin | Out-Null
$out = Join-Path $bin 'DSLRWebcamStudio.exe'
$sources = @(Get-ChildItem (Join-Path $root 'src') -Filter *.cs | ForEach-Object { $_.FullName }) + $appInfo

& $csc -nologo -target:winexe -platform:x64 -optimize+ -unsafe+ -warn:4 `
    "-out:$out" `
    "-win32manifest:$(Join-Path $root 'app.manifest')" `
    "-win32icon:$(Join-Path $repo 'assets\icon.ico')" `
    -reference:System.Drawing.dll -reference:System.Windows.Forms.dll `
    $sources
if ($LASTEXITCODE -ne 0) { throw "build failed" }
"Built $out v$version ({0:N0} KB)" -f ((Get-Item $out).Length / 1KB)
