// Generated by build.sh from VERSION and DONATE_URL. Do not edit.
enum AppInfo {
    static let version = "1.0.0"
    static let donateURL = "https://paypal.me/shekhawatakshay"
    static let repoURL = "https://github.com/akshay4/dslr-webcam-studio"
    // The button stays hidden until DONATE_URL holds a real link.
    static var donateConfigured: Bool { !donateURL.contains("YOUR_PAYPAL_NAME") && donateURL.hasPrefix("https://") }
}
