#!/usr/bin/env bash
# Builds "DSLR Webcam Studio.app" (universal: Apple silicon + Intel) and a zip for release.
# Requires Xcode command line tools (swift, iconutil, codesign). Run on macOS.
set -euo pipefail
cd "$(dirname "$0")"
VERSION=$(cat ../VERSION)
DONATE=$(cat ../DONATE_URL)

# Version and donation link come from the repo-root files shared by all three apps.
cat > Sources/DSLRWebcamStudio/AppInfo.swift <<EOF
// Generated by build.sh from VERSION and DONATE_URL. Do not edit.
enum AppInfo {
    static let version = "$VERSION"
    static let donateURL = "$DONATE"
    static let repoURL = "https://github.com/akshay4/dslr-webcam-studio"
    // The button stays hidden until DONATE_URL holds a real link.
    static var donateConfigured: Bool { !donateURL.contains("YOUR_PAYPAL_NAME") && donateURL.hasPrefix("https://") }
}
EOF

swift build -c release --arch arm64 --arch x86_64
BIN=$(swift build -c release --arch arm64 --arch x86_64 --show-bin-path)/DSLRWebcamStudio
"$BIN" --selftest

APP="build/DSLR Webcam Studio.app"
rm -rf build && mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/DSLRWebcamStudio"
sed "s/__VERSION__/$VERSION/g" Info.plist > "$APP/Contents/Info.plist"

ICONSET=build/AppIcon.iconset
mkdir -p "$ICONSET"
for s in 16 32 128 256 512; do
    cp "../assets/icon_$s.png" "$ICONSET/icon_${s}x${s}.png"
    cp "../assets/icon_$((s * 2)).png" "$ICONSET/icon_${s}x${s}@2x.png"
done
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/AppIcon.icns"

# Ad-hoc signature: required for Apple silicon to launch it. Not notarized (see README for first launch).
codesign --force --deep --sign - "$APP"
(cd build && ditto -c -k --keepParent "DSLR Webcam Studio.app" "DSLR_Webcam_Studio-$VERSION-macOS.zip")
ls -la build/*.zip
